# Note: This is not a full icon theme, don't apply it by itself without changing the inherits.

[Icon Theme]
# Add `ProtonVPN-symbolic` to the Inherits field in the index.theme of the icon theme that you're using (before anything that could override it).
# Example: Inherits=ProtonVPN-symbolic,Adwaita,hicolor
# IMPORTANT: DON'T PUT SPACES!
# Alternatively, you can put the name of the icon theme that you want to use in the Inherits field below and apply this as your icon theme.
# For example, if you want to use Papirus, it should be `Inherits=Papirus` (again, no spaces)
# You could also manually copy-paste the icons to the icon pack you want to use.

Inherits=

Name=Symbolic ProtonVPN
Comment=Proper symbolic icons for Proton VPN tray indicator
Example=protonvpngui-connected

FollowsColorScheme=true

DesktopDefault=48
DesktopSizes=16,22,24,32,48,64
ToolbarDefault=22
ToolbarSizes=16,22,24,32,48
MainToolbarDefault=22
MainToolbarSizes=16,22,24,32,48
SmallDefault=16
SmallSizes=16,22,24,32,48
PanelDefault=48
PanelSizes=16,22,24,32,48,64
DialogDefault=48
DialogSizes=16,22,24,32,48,64

# Directory list
Directories=16x16,22x22,24x24
ScaledDirectories=16x16@2x,22x22@2x,24x24@2x

[16x16]
Context=Status
Size=16
Type=Fixed

[16x16@2x]
Context=Status
Size=16
Scale=2
Type=Fixed

[22x22]
Context=Status
Size=22
Type=Fixed

[22x22@2x]
Context=Status
Size=22
Scale=2
Type=Fixed

[24x24]
Context=Status
Size=24
Type=Fixed

[24x24@2x]
Context=Status
Size=24
Scale=2
Type=Fixed
